name: Keep Render Awake

on:
  schedule:
    # Runs every 10 minutes (GitHub Actions cron syntax)
    - cron: "*/9 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          echo "Pinging Render service to keep it awake..."
          curl -m 10 -s https://interactive-cv-backend-latest.onrender.com || echo "Ping failed"
